version: 0.2
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - cd app ; go build -o hello main.o
      - pwd
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app/hello
