version: 0.2
phases:
  install:
    commands:
      - go get github.com/leonegeo/demoapp-gocommon
      - go get github.com/stretchr/testify/assert
      - go get -u github.com/golang/lint/golint
  pre_build:
    commands:
      - golint -set_exit_status
      - go test
  build:
    commands:
      - go build
  post_build:
    commands:
      - echo no postbuild commands
artifacts:
  files:
    - demoapp-hello
