version: 0.2
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - go get github.com/leonegeo/demoapp-gocommon
      - go get github.com/stretchr/testify/assert
      - ls -R $GOPATH
      - pwd
      - ls -R
      - cd app ; go build -o hello main.go
      - pwd
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app/hello
